### ISSUE TITLE
Set up Approvals Worfklow in GitHub

### ISSUE THREAD

**Issue by Henrique-mazzoleni** [The-Ironsquad/Tender#4]
Protect the main branch from unapproved merging.

**Comment by Henrique-mazzoleni** [comment]
So, I worked directly on the main branch and committed without making a pull request and I saw that Zefanja did the same.  I have protected the main branch just so we don't forget not to do that anymore. The rest of the workflow still needs to be implemented.

**Comment by hiranimotors** [comment]
What else is there to do for this task?

**Comment by Henrique-mazzoleni** [comment]
It depends how we setup the branches

**Comment by Henrique-mazzoleni** [comment]
I have protected the `develop` and `production` branches. You can only commit changes with a pull request and the pull request has to be approved by someone else. I had initially put the requirement that 2 reviewers had to approve the code but given that everybody has very little time to spend on these projects I have reduced to 1 reviewer. I'll close this issue for now but if anybody wants to discuss this approval settings further you are welcome to reopen it
